# Generated by Django 3.2.9 on 2021-12-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='user',
            name='family_status',
            field=models.CharField(choices=[('a', 'Не женат'), ('b', 'Женат'), ('c', 'В активном поиске'), ('d', 'Все сложно'), ('q', 'Не указано')], default='q', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужчина'), ('F', 'Женщина'), ('N', 'Не указанно')], default='N', max_length=1),
        ),
    ]
